name: Update Vacation Balance

on:
  schedule:
    - cron: "0 0 * * *" # Runs at midnight UTC
  workflow_dispatch: # Allows manual trigger for testing

jobs:
  update-balance:
    runs-on: ubuntu-latest

    steps:
      - name: Update vacation balance
        id: update
        run: |
          ENDPOINT="${{ secrets.APP_URL }}/api/updateUserVacationBalance"
          echo "Calling endpoint: $ENDPOINT"

          response=$(curl -v -X POST "$ENDPOINT" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -w "\n%{http_code}" \
            -f)
            
          if [ $? -ne 0 ]; then
            echo "::error::Failed to call the API endpoint"
            exit 1
          fi

          echo "Response: $response"
